application: syndicate-metadata
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- warmup

builtins:
- appstats: on
- admin_redirect: on
- deferred: on

handlers:
- url: /syn.*
  script: django_syndicate_web.wsgi.application
  secure: always

- url: .*
  script: ms.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: lxml
  version: latest
- name: pycrypto
  version: latest
- name: django
  version: latest

